// prisma/seed-helpers.ts
export function seedCharacters() {
  return [
    { name: "Baba Six", role: "Leader / fixer", height: "~6 inches", color: "Cream & brown", bibleDetails: "Dark warm-brown skin; sturdy adult build; weathered friendly face; short black/grey hair; grey-black moustache; cream short-sleeve shirt; dark brown trousers; worn brown sandals; vintage wristwatch; small leather cross-body tool pouch; tiny adjustable wrench. Calm, confident, stubborn, practical. Signature phrase: Leave am for me." },
    { name: "Kola", role: "Hustler / delivery guy", height: "~5.8 inches", color: "Orange & charcoal", bibleDetails: "Medium-dark warm-brown skin; slim athletic adult build; youthful adult face; short low-cut black hair; tiny moustache; bright orange delivery vest; charcoal T-shirt; dark navy utility trousers; black sneakers; black wristwatch; oversized dark charcoal delivery backpack; smartphone. Energetic, fast-talking, reckless. Signature phrase: No wahala." },
    { name: "Amaka", role: "Engineer / strategist", height: "~6 inches", color: "Forest green & black", bibleDetails: "Warm medium-brown skin; slim healthy adult build; oval face; expressive dark-brown eyes; full natural brows; medium Nigerian nose; soft full lips; shoulder-length natural-textured black hair in neat practical braids; dark forest-green utility jumpsuit; dark work boots; black utility belt; protective goggles on head; digital watch; rugged tablet. Calm, analytical, quietly sarcastic." },
    { name: "Uncle T", role: "Old-school mechanic / inventor", height: "~5.5 inches", color: "Faded blue", bibleDetails: "Deep brown skin; compact older-adult build; balding head with short grey hair at sides; realistic grey beard; round reading glasses; faded blue mechanic overalls; light work shirt; worn work boots; suspenders; overflowing tool belt. Inventive, stubborn, calm, resourceful. Signature prop: ridiculously long piece of wire. Signature phrase: Experience." },
    { name: "Small", role: "Scout / climber / unexpected hero", height: "~4.5 inches", color: "Bright yellow", bibleDetails: "Dark brown skin; round expressive adult face; short curly black hair; compact athletic adult build; bright yellow T-shirt; dark shorts; tiny sneakers; small dark backpack. Quiet, observant, underestimated, brave, resourceful. Signature phrase: Watch me." },
  ];
}
